import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import FadeInMotion from '@/animation/FadeInMotion';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <FadeInMotion>
          <Navbar />
          {children}
          <div className=' xl:mt-24'>
            <Footer />
          </div>
        </FadeInMotion>
      </body>
    </html>
  );
}
